---
abstract: 'the Go lang Interface style duck type checker'
author:
  - 'Kazuhiro Osawa <yappo <at> shibuya <döt> pl>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-InterfaceType
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Scalar::Util: 0
resources:
  homepage: http://github.com/yappo/p5-Object-InterfaceType/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yappo/p5-Object-InterfaceType.git
version: 0.01
